<a href="https://colab.research.google.com/github/zaedulislam/PyTorch_for_Deep_Learning_and_Computer_Vision/blob/main/Section%203%20-%20Intro%20to%20Tensors%20-%20PyTorch/10.%20Matrix%20Multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notion Page: https://www.notion.so/islamzaedul/Section-3-Intro-to-Tensors-PyTorch-00312679b16344739b86e8636e470770#6bff813e2df7488ea7decf3d78cbb688

In [1]:
!pip3 install torch

In [2]:
import torch

# 10. Matrix Multiplication

In [3]:
mat_a = torch.tensor([0, 3, 5, 5, 5, 2]).view(2, 3)
mat_a

tensor([[0, 3, 5],
        [5, 5, 2]])

In [4]:
mat_b = torch.tensor([3, 4, 3, -2, 4, -2]).view(3, 2)
mat_b

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [5]:
torch.matmul(mat_a, mat_b)

tensor([[ 29, -16],
        [ 38,   6]])