<a href="https://colab.research.google.com/github/zaedulislam/PyTorch_for_Deep_Learning_and_Computer_Vision/blob/main/Section%203%20-%20Intro%20to%20Tensors%20-%20PyTorch/10.%20Matrix%20Multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 10. Matrix Multiplication

Notion Page: https://www.notion.so/zaedulislam/Section-3-Intro-to-Tensors-PyTorch-ec1c8bad7a0a4af0b64f18f80eeb2779#277286992ebc495ba898143560814dfa

In [ ]:
!pip3 install torch

In [ ]:
import torch

In [ ]:
mat_a = torch.tensor([0, 3, 5, 5, 5, 2]).view(2, 3)
mat_a

tensor([[0, 3, 5],
        [5, 5, 2]])

In [ ]:
mat_b = torch.tensor([3, 4, 3, -2, 4, -2]).view(3, 2)
mat_b

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [ ]:
torch.matmul(mat_a, mat_b)

tensor([[ 29, -16],
        [ 38,   6]])