<a href="https://colab.research.google.com/github/zaedulislam/PyTorch_for_Deep_Learning_and_Computer_Vision/blob/main/Section%203%20-%20Intro%20to%20Tensors%20-%20PyTorch/Intro_to_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 6. 1 Dimensional Tensors

Notion Page: https://www.notion.so/islamzaedul/Section-3-Intro-to-Tensors-PyTorch-00312679b16344739b86e8636e470770#e4321bce9ad54cb788e89d374c25b39e

In [20]:
!pip3 install torch

In [53]:
import torch
import numpy as np

In [22]:
# Create a 1D tensor
v = torch.tensor([1, 2, 3, 4, 5, 6])
print(v)

tensor([1, 2, 3, 4, 5, 6])


In [23]:
# To determine the datatype contained in the tensor
print(v.dtype)

torch.int64


In [24]:
# Indexing a tenser is very similar to how we would index a python list
print(v[2])

tensor(3)


In [25]:
# Slice from index one to Index four. And notice that returns the integers that indices one, two and three, it does not grab the integer at index four since the stop index is exclusive.
print(v[1:4])

tensor([2, 3, 4])


In [26]:
# To grab everything from index one and beyond, we can simply use the same shortcut as what would for Python
print(v[1:])

tensor([2, 3, 4, 5, 6])


In [27]:
f = torch.FloatTensor([1, 2, 3, 4, 5, 6])

In [28]:
print(f)

tensor([1., 2., 3., 4., 5., 6.])


In [29]:
print(f.dtype)

torch.float32


In [30]:
# Determine the size of the tensor
print(f.size())

torch.Size([6])


In [35]:
# View the 1D tenor(v) as six rows of data in a single column. It's similar to reshape method of numpy to reshape an array
v.view(6, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [32]:
print(v)

tensor([1, 2, 3, 4, 5, 6])


In [45]:
# What we rearrange, our tensor must be compatible with your original input, i.e. if we were to rearrange the tensor into seven rows in one column. 
# It would throw an error, since I we have six elements which would be insufficient to make seven rows out of it.
v.view(7, 1)

RuntimeError: ignored

In [46]:
v.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

### We can interchangeably switch between numpy arrays and tensors.

In [50]:
# If we don't want to explicitely specity the number of column, use -1 and let the Pytorch decide for us
v.view(3, -1)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [57]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [56]:
# Transform a numpy array to a tensor
tensor_cnv = torch.from_numpy(a)
print(tensor_cnv)

tensor([1, 2, 3, 4, 5])


In [61]:
# Tansform a tensor to a numpy array
numpy_cnv = tensor_cnv.numpy()
print(numpy_cnv)

[1 2 3 4 5]
