<a href="https://colab.research.google.com/github/zaedulislam/PyTorch_for_Deep_Learning_and_Computer_Vision/blob/main/Section%203%20-%20Intro%20to%20Tensors%20-%20PyTorch/8.%202%20Dimensional%20Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notion Page: https://www.notion.so/islamzaedul/Section-3-Intro-to-Tensors-PyTorch-00312679b16344739b86e8636e470770#db1106190fca44f48f87eee5311b1d09

In [7]:
!pip3 install torch

In [8]:
import torch

# 8. 2 Dimensional Tensors

**Initialize a 1D tensor containing a numbers from 2 to 6. This is similar to the range function in python**

In [9]:
one_d = torch.arange(2, 7)
one_d

tensor([2, 3, 4, 5, 6])

In [10]:
print('A -> ', torch.arange(7))
print('B -> ', torch.arange(0, 7))

A ->  tensor([0, 1, 2, 3, 4, 5, 6])
B ->  tensor([0, 1, 2, 3, 4, 5, 6])


**A step size of two, which specifies the gap between each pair of points**
> start (Number) – the starting value for the set of points. Default: 0.

> end (Number) – the ending value for the set of points

> step (Number) – the gap between each pair of adjacent points. Default: 1.

In [11]:
one_d_gap = torch.arange(start = 2, end = 9, step = 2)
one_d_gap

tensor([2, 4, 6, 8])

In [12]:
one_d = torch.arange(0, 9)
two_d = one_d.view(3, 3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

**Confirm the dimensionality of this matrix**

In [13]:
two_d.dim()

2

**Slice 2D tensor**

In [14]:
two_d[1, 2]

tensor(5)

**The best way to think about this 3D tensor is imagine an Excel spreadsheet with "two sheets" and each sheet has three rows and three columns**

In [15]:
x = torch.arange(18).view(2, 3, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

**So long as that new shape of that tensor, its new dimensions must be compatible with the array's data**

In [16]:
x = torch.arange(18).view(3, 3, 2)
x

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])

**If we try to put four columns per block. That wouldn't work if there was an exception, since four times, three times three does not correspond to 18 elements, it corresponds to thirty six elements, in which case it would work**

In [18]:
x = torch.arange(18).view(3, 3, 4)
x

RuntimeError: ignored