<a href="https://colab.research.google.com/github/zaedulislam/PyTorch_for_Deep_Learning_and_Computer_Vision/blob/main/Section%203%20-%20Intro%20to%20Tensors%20-%20PyTorch/8.%202%20Dimensional%20Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 8. 2 Dimensional Tensors

Notion Page: https://www.notion.so/zaedulislam/Section-3-Intro-to-Tensors-PyTorch-ec1c8bad7a0a4af0b64f18f80eeb2779#027e9b42177b474c8a4dd2d3ba0abe03

In [1]:
!pip3 install torch

In [2]:
import torch

In [3]:
# Initialize a 1D tensor containing a numbers from 2 to 6. This is similar to the range function in python
one_d = torch.arange(2, 7)
one_d

tensor([2, 3, 4, 5, 6])

In [4]:
print('A -> ', torch.arange(7))
print('B -> ', torch.arange(0, 7))

A ->  tensor([0, 1, 2, 3, 4, 5, 6])
B ->  tensor([0, 1, 2, 3, 4, 5, 6])


In [5]:
#  A step size of two, which specifies the gap between each pair of points
one_d_gap = torch.arange(2, 9, 2)
one_d_gap

tensor([2, 4, 6, 8])

In [6]:
one_d = torch.arange(0, 9)
two_d = one_d.view(3, 3)
two_d

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [7]:
# Confirm the dimensionality of this matrix 
two_d.dim()

2

In [8]:
# Slice 2D tensors
two_d[1,2]

tensor(5)

In [9]:
x = torch.arange(18).view(2, 3, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])