<a href="https://colab.research.google.com/github/zaedulislam/PyTorch_for_Deep_Learning_and_Computer_Vision/blob/main/Section%203%20-%20Intro%20to%20Tensors%20-%20PyTorch/9.%20Slicing%203D%20Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 9. Slicing 3D Tensors

Notion Page: https://www.notion.so/zaedulislam/Section-3-Intro-to-Tensors-PyTorch-ec1c8bad7a0a4af0b64f18f80eeb2779#785c1ff380d94c7aa28acb607ffdf5ff

In [ ]:
!pip3 install torch 

In [ ]:
import torch

In [ ]:
x = torch.arange(18).view(3, 2, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [ ]:
x[2, 1, 2]

tensor(17)

In [ ]:
x[1, 0:2, 0:3]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [ ]:
# Since we're slicing all two rows, we can simply omit the range and it will be inferred as such
x[1, :, 0:3]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [ ]:
# Since we're slicing all three columns, we can simply omit the range and it will be inferred as such
x[1, 0:2, :]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])