<a href="https://colab.research.google.com/github/zaedulislam/PyTorch_for_Deep_Learning_and_Computer_Vision/blob/main/Section%203%20-%20Intro%20to%20Tensors%20-%20PyTorch/9.%20Slicing%203D%20Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notion Page: https://www.notion.so/islamzaedul/Section-3-Intro-to-Tensors-PyTorch-00312679b16344739b86e8636e470770#d0b721c386e0425bab317f2e8f157c3f

In [12]:
!pip3 install torch 

In [13]:
import torch

# 9. Slicing 3D Tensors

In [14]:
x = torch.arange(18).view(3, 2, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

In [15]:
x[2, 1, 2]

tensor(17)

**Parameters:**

> tensor_position_start: Specifies the Tensor to start iterating

> tensor_position_end: Specifies the Tensor to stop iterating

> tensor_dimension_start: Specifies the Tensor to start the iteration of tensor in given positions

> tensor_dimension_stop: Specifies the Tensor to stop the iteration of tensor in given positions

>  tensor_value_start: Specifies the start position of the  tensor to iterate the elements given in dimensions

> tensor_value_stop: Specifies the end position of the tensor to iterate the elements given in dimensions

In [22]:
x[1, 0:2, 0:3]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

**Since we're slicing all two rows, we can simply omit the range and it will be inferred as such**

In [17]:
x[1, :, 0:3]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

**Since we're slicing all three columns, we can simply omit the range and it will be inferred as such**

In [18]:
x[1, 0:2, :]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])