<a href="https://colab.research.google.com/github/zaedulislam/PyTorch_for_Deep_Learning_and_Computer_Vision/blob/main/Section%204%20-%20Linear%20Regression%20-%20PyTorch/15.%20Linear%20Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notion Page: https://www.notion.so/islamzaedul/Section-4-Linear-Regression-PyTorch-07e980b180d1420a8703e1df0fae6a83#f7b42c37d45e41a2b2f6c4edf7a27068

In [12]:
!pip3 install torch

In [13]:
import torch
from torch.nn import Linear

In [14]:
torch.manual_seed(1)

# Creating a linear model
# What this means is that for every prediction that we make using our linear model for every output, there is a single input.
model = Linear(in_features=1, out_features=1)

# "model.weight" -> m
# "model.bias" -> b

print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [15]:
x = torch.tensor([2.0])
print(model(x))

tensor([0.5891], grad_fn=<AddBackward0>)


In [16]:
x = torch.tensor([[2.0], [3.3]])
print(model(x))

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward0>)
