<a href="https://colab.research.google.com/github/zaedulislam/PyTorch_for_Deep_Learning_and_Computer_Vision/blob/main/Section%204%20-%20Linear%20Regression%20-%20PyTorch/16.%20Custom%20Modules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notion Page: https://www.notion.so/islamzaedul/Section-4-Linear-Regression-PyTorch-07e980b180d1420a8703e1df0fae6a83#8652666b7ca4418cb4995cb2ef45661c

In [24]:
!pip3 install torch

In [25]:
import torch
import torch.nn as nn

## Making predictions using the linear class in an object oriented programming approach 

### Boilerplate code that is always needed to write to create a custom class

In [26]:
# We will use inheritance such that this subclass will leverage code from our base class and then the module.
# "Module" -> Module itself will typically act as a base class for all neural network modules.
# In this case, the linear regression model class (LR) will be a subclass of nn.Module, thereby inherit methods and variables from this parent class.

class LR(nn.Module):
    # We use this constructor to initialize new instances of the class 
    # "self" simply represents the instance of the class, the object that's yet to be initialized.
    def __init__(self, input_size, output_size):
        # When dealing with class inheritance, one should be mindful of calling super().__init_(). Which simply allows for more 
        # freedom in the use of multiple inheritance from parent classes.
        super().__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        pred = self.linear(x)
        return pred


In [27]:
# Random number generator
torch.manual_seed(1)

model = LR(1, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [28]:
x = torch.tensor([1.0])
print(model.forward(x))

tensor([0.0739], grad_fn=<AddBackward0>)


In [29]:
x = torch.tensor([[1.0], [2.0]])
print(model.forward(x))

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward0>)
