<a href="https://colab.research.google.com/github/zaedulislam/PyTorch_for_Deep_Learning_and_Computer_Vision/blob/main/Section%2014%20-%20Appendix%20B%20-%20NumPy%20Crash%20Course%20(Optional)/90.%20Arrays%20vs%20Lists.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notion Page: https://www.notion.so/islamzaedul/Section-14-Appendix-B-NumPy-Crash-Course-Optional-8fb9170a96474ee098238fa8d0aeb73b#ca3df464f3734a919616e7460b6d64cc

## Python List

In [14]:
listA = list(range(1, 4))
listB = list(range(1, 4))
listSum = []

for index in range(3):
    listA[index] = listA[index] ** 2
    listB[index] = listB[index] ** 3

    listSum.append(listA[index] + listB[index])

print(listSum)

[2, 12, 36]


## numpy Array
It also goes beyond convenience as an numpy is also have smaller memory consumption and high performance relative to their Python counterpart array when reading or writing from several large terabyte files.

In [15]:
import numpy as np

arrayA = np.arange(1, 4) ** 2
arrayB = np.arange(1, 4) ** 3
arraySum = arrayA + arrayB

print(arrayA)
print(arrayB)
print(arraySum)

[1 4 9]
[ 1  8 27]
[ 2 12 36]


In [16]:
np.power(np.array([1, 2, 3]), 4)

array([ 1, 16, 81])

In [17]:
np.array([1, 2, 3]) ** 4

array([ 1, 16, 81])

In [18]:
np.negative(np.array([1, 2, 3]))

array([-1, -2, -3])

In [19]:
np.array([1, 2, 3]) * (-1)

array([-1, -2, -3])

In [20]:
np.exp(np.array([1, 2, 3]))

array([ 2.71828183,  7.3890561 , 20.08553692])

In [21]:
np.log(np.array([1, 2, 3]))

array([0.        , 0.69314718, 1.09861229])

In [22]:
np.sin(np.array([1, 2, 3]))

array([0.84147098, 0.90929743, 0.14112001])