<a href="https://colab.research.google.com/github/zaedulislam/PyTorch_for_Deep_Learning_and_Computer_Vision/blob/main/Section%2014%20-%20Appendix%20B%20-%20NumPy%20Crash%20Course%20(Optional)/90.%20Arrays%20vs%20Lists.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notion Page: https://www.notion.so/islamzaedul/Section-14-Appendix-B-NumPy-Crash-Course-Optional-8fb9170a96474ee098238fa8d0aeb73b#ca3df464f3734a919616e7460b6d64cc

In [ ]:
import numpy as np

### Python List vs numpy Array

1. A one dimensional or multidimensional array generally consists of a homogeneous group of values that are all of the same type, whereas lists would be the python equivalent of an array but are heterogeneous in the sense that they generally contain, generally contain elements of different types. This is the most obvious difference.

2. A more subtle difference lies in their functionality. Numpty arrays allow vectorized operation such as Element Y's addition and multiplication, which is
a lot more concise than how it would be done with Python lists.






## Python List

In [ ]:
listA = list(range(1, 4))
listB = list(range(1, 4))
listSum = []

for index in range(3):
    listA[index] = listA[index] ** 2
    listB[index] = listB[index] ** 3

    listSum.append(listA[index] + listB[index])

print(listSum)

[2, 12, 36]


## numpy Array
It also goes beyond convenience as an numpy is also have smaller memory consumption and high performance relative to their Python counterpart array when reading or writing from several large terabyte files.

In [ ]:
arrayA = np.arange(1, 4) ** 2
arrayB = np.arange(1, 4) ** 3
arraySum = arrayA + arrayB

print(arrayA)
print(arrayB)
print(arraySum)

[1 4 9]
[ 1  8 27]
[ 2 12 36]


In [ ]:
np.power(np.array([1, 2, 3]), 4)

array([ 1, 16, 81])

In [ ]:
np.array([1, 2, 3]) ** 4

array([ 1, 16, 81])

In [ ]:
np.negative(np.array([1, 2, 3]))

array([-1, -2, -3])

In [ ]:
np.array([1, 2, 3]) * (-1)

array([-1, -2, -3])

In [ ]:
np.exp(np.array([1, 2, 3]))

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.log(np.array([1, 2, 3]))

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.sin(np.array([1, 2, 3]))

array([0.84147098, 0.90929743, 0.14112001])

# Element-Wise Multiplication in NumPy

## 1. Element-Wise Multiplication (also known as Hadamard Product) of Matrices in Python Using the `np.multiply()` Method 

https://www.delftstack.com/howto/numpy/element-wise-multiplication-python/

<p>In element-wise matrix multiplication (also known as Hadamard Product), every element of the first matrix is multiplied by the second matrix’s corresponding element.</p>

<p>When performing the element-wise matrix multiplication, both matrices should be of the same dimensions. The resultant matrix <code>c</code> of the element-wise matrix multiplication <code>a*b = c</code> always has the same dimension as that in <code>a</code> and <code>b</code>.<span id="ezoic-pub-ad-placeholder-113" class="ezoic-adpicker-ad"></span><span class="ezoic-ad medrectangle-3 medrectangle-3113 adtester-container adtester-container-113" data-ez-name="delftstack_com-medrectangle-3" style=""><span id="div-gpt-ad-delftstack_com-medrectangle-3-0" ezaw="728" ezah="90" style="position: relative; z-index: 0; display: inline-block; padding: 0px; min-height: 90px; min-width: 728px;" class="ezoic-ad"><script data-ezscrex="false" data-cfasync="false" style="display:none">if(typeof __ez_fad_position!='undefined'){__ez_fad_position('div-gpt-ad-delftstack_com-medrectangle-3-0')};</script><div id="google_ads_iframe_/1254144,21871662888/delftstack_com-medrectangle-3_0__container__" style="border: 0pt none; width: 728px; height: 0px;"></div></span></span></p>

In [ ]:
a1 = np.array([[12,46,23,7,2],[3,5,8,3,6]])
a2 = np.array([[15,26,2,17,22],[13,8,9,3,4]])

print(np.multiply(a1,a2))

[[ 180 1196   46  119   44]
 [  39   40   72    9   24]]
