<a href="https://colab.research.google.com/github/zaedulislam/PyTorch_for_Deep_Learning_and_Computer_Vision/blob/main/Section%2014%20-%20Appendix%20B%20-%20NumPy%20Crash%20Course%20(Optional)/91.%20Multidimensional%20Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notion Page: https://www.notion.so/islamzaedul/Section-14-Appendix-B-NumPy-Crash-Course-Optional-8fb9170a96474ee098238fa8d0aeb73b#fd9d483d2f4344a1b3153428a741ed1c

In [1]:
 import numpy as np

In [3]:
x = np.arange(3)
x

array([0, 1, 2])

In [7]:
y = np.arange(0, 3)
y

array([0, 1, 2])

In [6]:
z = np.arange(0, 3)
z

array([0, 1, 2])

In [10]:
multiDimensionalArray = np.array([x, y, z])
print(multiDimensionalArray)
print(multiDimensionalArray.shape)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
(3, 3)


## arange vs linspace

In [32]:
#  A one dimensional array of numbers between one and ten. More specifically, it returns 50 numbers and all numbers are evenly spaced
m = np.linspace(1, 10, 50)
m

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [37]:
# This third argument (step) specifies how many elements we want from one to 10
n = np.arange(1, 10, step=3)
n

array([1, 4, 7])

In [17]:
a = np.arange(3)
b = np.arange(3, 6)
c = np.arange(6, 9)

multiDimensionalArray = np.array([a, b, c])
print(multiDimensionalArray)
print(multiDimensionalArray.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [24]:
print(multiDimensionalArray.dtype)

int64


### Accessing Element

In [19]:
multiDimensionalArray[1][2]

5

In [20]:
multiDimensionalArray[1, 2]

5

### Defining Array Type

In [29]:
p = np.array([1, 4], dtype=np.int16)
print(p)
print(p.dtype)

[1 4]
int16
