<a href="https://colab.research.google.com/github/zaedulislam/PyTorch_for_Deep_Learning_and_Computer_Vision/blob/main/Section%2014%20-%20Appendix%20B%20-%20NumPy%20Crash%20Course%20(Optional)/92.%20One%20Dimensional%20Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

In [14]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# "start" index is inclusive
# "stop" index is exclusive
print(x[2:7])

[3 4 5 6 7]


In [16]:
# If starting index is omitted, it assumes that we're going to start at the very beginning of the list up until your stop index minus one
# "stop" index is exclusive
print(x[:7])

[1 2 3 4 5 6 7]


In [17]:
# If the stop index is omitted, it automatically assumes that we want everything in the array beyond the start index 
print(x[:])

[1 2 3 4 5 6 7 8 9]


In [18]:
 print(x[2:7:2])

[3 5 7]
