<a href="https://colab.research.google.com/github/zaedulislam/PyTorch_for_Deep_Learning_and_Computer_Vision/blob/main/Section%2014%20-%20Appendix%20B%20-%20NumPy%20Crash%20Course%20(Optional)/93.%20Reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notion Page: https://www.notion.so/islamzaedul/Section-14-Appendix-B-NumPy-Crash-Course-Optional-8fb9170a96474ee098238fa8d0aeb73b#959d1bf698954e209667a6b886235f29

In [4]:
import numpy as np

In [5]:
x = np.arange(9)

print(x)

[0 1 2 3 4 5 6 7 8]


### reshape(...) changes the shape of an array. According to a pupil of integers, the new shape of that array, its new dimensions must be compatible with the arrays data.

In [10]:
# Dimension must be compatible with data
y = np.arange(9).reshape(3,3)

print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
y = np.arange(9).reshape(3,2)

print(y)

ValueError: ignored

In [12]:
# "-1" denotes a unknown dimension, the number of columns will be determined in a way such that the overal number of elements
# must work out to 9 (size of the initial 1D array)
a = np.arange(9).reshape(3, -1)

print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
b = np.arange(18).reshape(2, 3, 3)

print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [14]:
c = np.arange(18).reshape(3, 3, 2)

print(c)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
